version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
  api:
    build:
      dockerfile: Dockerfile
      context: ./server

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - CHOKIDAR_USEPOLLING=true
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client

  worker:
    build:
      dockerfile: Dockerfile
      context: ./worker

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

